### ISSUE TITLE
一点小错误 

### ISSUE THREAD

**Issue by sdbaiguanghe** [rainyear/lolita#17]
包名在引用时应该引用到最后一层目录的名称，在使用时只用最后一层目录名称作为包名
这句是不对的，在使用时不是使用最后一层目录作为包名，而是使用该目录下的唯一package名称
比如 test/a 目录下有个package b包，你引用"test/a" 使用时要用b.Something

**Comment by rainyear** [comment]
@sdbaiguanghe 谢谢指正！

良好的习惯应该是保存package名与目录名一致吧。

另外，如果有问题可以直接在原文下面加评论，不需要重新开一个issue :smile:

**Comment by sdbaiguanghe** [comment]
不好意思，我是开了一个issue后才发现不该开的，开了又不能删除只能关闭，所以没再管。
